### PR TITLE
adding MOC Alliance & OpenInfra Labs Logo & Link v3

### PR DESCRIPTION
**Pull request by schwesig**
This PR is v3 https://github.com/operate-first/operate-first.github.io/pull/188 -> [preview](https://deploy-preview-188--operate-first-cloud.netlify.app/); all logos to the right, using the white version of the logos, adding an `Affiliates` link, removing text `Operate First is a Red Hat initiative`

After merging v4 for a quick release, this v3 is now adding the affiliations link and page.

These are competing PRs over different designs. In the end, we will merge one:
Basis:
- Adding Logo and Link for MOC Alliance and OpenInfra Labs
- in the footer of all pages at [operate-first.cloud](https://operate-first.cloud)

v1 https://github.com/operate-first/operate-first.github.io/pull/186 -> [preview](https://deploy-preview-186--operate-first-cloud.netlify.app/) leaving Red Hat logo where it is, adding partner logos to the right, using the color version of the logos
v2 https://github.com/operate-first/operate-first.github.io/pull/187 -> [preview](https://deploy-preview-187--operate-first-cloud.netlify.app/) leaving Red Hat logo where it is, adding partner logos to the right, using the white version of the logos
v3 https://github.com/operate-first/operate-first.github.io/pull/188 -> [preview](https://deploy-preview-188--operate-first-cloud.netlify.app/) all logos to the right, using the white version of the logos, adding an `Affiliates` link, removing text `Operate First is a Red Hat initiative`
v4 https://github.com/operate-first/operate-first.github.io/pull/189 -> [preview](https://deploy-preview-189--operate-first-cloud.netlify.app/) all logos to the right, using the white version of the logos, no `Affiliates` link, removing text `Operate First is a Red Hat initiative`

Notes:
- as far as we know: The color version of the MOC Alliance & OpenInfra Labs logo has only dark grey/ black font, to make it visible, I change the font color to white (v1). This could be a violation of design rules. Feel free to update us on that.
- the `Affiliates` link/ linked page, is not yet ready/ decided on, therefore v3 can as is by now, will lead to a dummy page

### CODE REVIEW

**Comment by quaid** [comment]
This looks really good, but one thing we noticed:

- The padding around the Red Hat logo (for example) should be the same as the letter 'e' in the logo, but
- The template will squeeze all the logos together when the page is resized smaller, so
- This needs to be fixed but we can go live with the change while fixing this

**Comment by schwesig** [comment]
> * The padding around the Red Hat logo (for example) should be the same as the letter 'e' in the logo, but

https://www.redhat.com/en/about/brand/standards/logo?pfe-ulmovyr7i=logo-a

**Comment by schwesig** [comment]
v4 ws merged,
now using this v3 version to build the affiliate page
@quaid

**Comment by schwesig** [comment]
> * The padding around the Red Hat logo (for example) should be the same as the letter 'e' in the logo, but

I wasn't precise enough: the padding must be at least as ample as the 'e'; it doesn't have to be exact.

[image](https://www.redhat.com/en/about/brand/standards/logo?pfe-ulmovyr7i=logo-a&pfe-kud8b0308=logo-a)

**Pull request closed without merging**
