### PR TITLE
Community Cards

### PR DESCRIPTION
**Pull request by schwesig**

### CODE REVIEW

**Comment by schwesig** [comment]
wip is over,
this can be the first relase
/remove-do-not-merge

**Comment by schwesig** [comment]
fixes https://github.com/open-services-group/scrum/issues/11

**Comment by durandom** [comment]
good first draft.

1. Can we make the landing page a link as the whole card? Or at least the image and text? I think the small icon at the bottom is too small
2. Not sure about the issue and PR numbers, the open/close ratio probably needs explanation? But I like the attempt of creating a health indicator.
3. are the images ok regarding licensing?

**Comment by schwesig** [comment]
> good first draft.
> 
> 1. Can we make the landing page a link as the whole card? Or at least the image and text? I think the small icon at the bottom is too small

working on it

> 2. Not sure about the issue and PR numbers, the open/close ratio probably needs explanation? But I like the attempt of creating a health indicator.

I will think about it and find a better/easier-to-read solution.

> 3. are the images ok regarding licensing?

Operate First: yes, our own
OS Climate: tbd: should be, I am in contact with Erik to verify
All others: yes, pexels.com https://www.pexels.com/license/ `All photos and videos on Pexels are free to use.
Attribution is not required. Giving credit to the photographer or Pexels is not necessary but always appreciated.
You can modify the photos and videos from Pexels. Be creative and edit them as you like.`

**Comment by schwesig** [comment]
@durandom the cards are linked now in full size

**Pull request merged**
