### PR TITLE
[WIP] Community Cards

### PR DESCRIPTION
**Pull request by durandom**
prototype for adding cards to the community page.
based on the first example in https://ui.mantine.dev/category/article-cards

cc @schwesig

### CODE REVIEW

**Comment by schwesig** [comment]
acceptance criteria
- list of communities using the Operate First Community Cloud or Governance
  - DS, ACM, OSC, ...
  - inspect workloads on clusters (own or steered workloads)
  - inspect SIGs, WGs, SPs


for future ideas:
- what is active
  - workload
  - active community work (meetings, ...)
  - active repo work (issues, PRs)
  - DS ?

**Comment by schwesig** [comment]
https://github.com/open-services-group/scrum/issues/2

**Comment by durandom** [comment]
closing in favor of #180

**Pull request closed without merging**
