### PR TITLE
Definition of operate first

### PR DESCRIPTION
**Pull request by nijaba**
Karsten asked me to propose this post

### CODE REVIEW

**Comment by schwesig** [comment]
@nijaba Thanks for the post. I am okay with the index file, but I guess the .ds files are MacOS-related files?
@durandom, can we ignore them/ get rid of them?

**Comment by nijaba** [comment]
Sorry about the .DS_Store files, added them to .gitignore.

**Review by schwesig — COMMENTED** [review]
/lgtm
/approve

**Comment by durandom** [comment]
@nijaba we can merge https://github.com/operate-first/operate-first.github.io/pull/183 , which fixes the colon problems and has a preview, or you can cherry-pick https://github.com/operate-first/operate-first.github.io/pull/183/commits/3a35b519160ed1edb907bab6513e2b7b34b32147

**Comment by nijaba** [comment]
> @nijaba we can merge #183 , which fixes the colon problems and has a preview, or you can cherry-pick [3a35b51](https://github.com/operate-first/operate-first.github.io/commit/3a35b519160ed1edb907bab6513e2b7b34b32147)

Thanks for the fixes.  I cherry-picked them.

**Pull request merged**
