### PR TITLE
adding MOC Alliance & OpenInfra Labs Logo & Link v1

### PR DESCRIPTION
**Pull request by schwesig**
This PR is v1 https://github.com/operate-first/operate-first.github.io/pull/186 -> [preview](https://deploy-preview-186--operate-first-cloud.netlify.app/) leaving Red Hat logo where it is, adding partner logos to the right, using the color version of the logos

These are competing PRs over different designs. In the end, we will merge one:
Basis:
- Adding Logo and Link for MOC Alliance and OpenInfra Labs
- in the footer of all pages at [operate-first.cloud](https://operate-first.cloud)

v1 https://github.com/operate-first/operate-first.github.io/pull/186 -> [preview](https://deploy-preview-186--operate-first-cloud.netlify.app/) leaving Red Hat logo where it is, adding partner logos to the right, using the color version of the logos
v2 https://github.com/operate-first/operate-first.github.io/pull/187 -> [preview](https://deploy-preview-187--operate-first-cloud.netlify.app/) leaving Red Hat logo where it is, adding partner logos to the right, using the white version of the logos
v3 https://github.com/operate-first/operate-first.github.io/pull/188 -> [preview](https://deploy-preview-188--operate-first-cloud.netlify.app/) all logos to the right, using the white version of the logos, adding an `Affiliates` link, removing text `Operate First is a Red Hat initiative`
v4 https://github.com/operate-first/operate-first.github.io/pull/189 -> [preview](https://deploy-preview-189--operate-first-cloud.netlify.app/) all logos to the right, using the white version of the logos, no `Affiliates` link, removing text `Operate First is a Red Hat initiative`

Notes:
- as far as we know: The color version of the MOC Alliance & OpenInfra Labs logo has only dark grey/ black font, to make it visible, I change the font color to white (v1). This could be a violation of design rules. Feel free to update us on that.
- the `Affiliates` link/ linked page, is not yet ready/ decided on, therefore v3 can as is by now, will lead to a dummy page

### CODE REVIEW

**Comment by quaid** [comment]
@schwesig here are two versions with anti-aliasing that might look better:

MOCwordmark_RGB_small
MOCwordmark_white_small

**Comment by schwesig** [comment]
here a v2 white white logos in the footer
https://github.com/operate-first/operate-first.github.io/pull/187
--> preview https://deploy-preview-187--operate-first-cloud.netlify.app/

**Comment by quaid** [comment]
> here a v2 white white logos in the footer #187 --> preview https://deploy-preview-187--operate-first-cloud.netlify.app/

Between the two, I greatly prefer the all-white logos and think they look pretty good in the footer. I want to see some variations because I think we don't want to have the Red Hat logo alone on the side like that.

I'm also thinking we want a stand-alone affiliations page with a link in the footer. I'll look into mocking up what I'm thinking.

**Comment by quaid** [comment]
> I'm also thinking we want a stand-alone affiliations page with a link in the footer. I'll look into mocking up what I'm thinking.

This is the idea I have, basically (graphic hack-mockup):
footer-layout--quaid_v1

**Comment by schwesig** [comment]
> > I'm also thinking we want a stand-alone affiliations page with a link in the footer. I'll look into mocking up what I'm thinking.
> 
> This is the idea I have, basically (graphic hack-mockup): footer-layout--quaid_v1

see v3 https://github.com/operate-first/operate-first.github.io/pull/188

**Comment by quaid** [comment]
**MOCK-UP PREVIEWS**

Since

Existing footer layout, logos in white on right:
https://deploy-preview-187--operate-first-cloud.netlify.app/

White logos, all right side with "Affiliations" link:
- https://deploy-preview-188--operate-first-cloud.netlify.app/
https://deploy-preview-189--operate-first-cloud.netlify.app/
https://deploy-preview-190--operate-first-cloud.netlify.app/
https://deploy-preview-187--operate-first-cloud.netlify.app/

**Comment by schwesig** [comment]
v4 https://github.com/operate-first/operate-first.github.io/pull/189 --> [preview](https://deploy-preview-189--operate-first-cloud.netlify.app/)
- white logos
- all on the right side
- proxy affiliate link & page removed for now (first go live)

**Comment by schwesig** [comment]
closed
in favor of v4

**Pull request closed without merging**
