### PR TITLE
Testwithblog

### PR DESCRIPTION
**Pull request by traytorous**
Successfully built the website with the blog plugin. Fixed the navbar issue. Figured out what css to change to make the the blog look like the main website.

### CODE REVIEW

**Comment by traytorous** [comment]
I created another test branch that had the blog features added to it. I feel I have successfully merged the two together repositories together into one. I've also fixed the css issue that was making the icon overlap with the the homepage. The only problem that I am having now is that I could not figure out what component made it so that the about page would switch to the blog. I had to rename the about page to purpose. The branch is up to date however any new changes that needs to be merged into the about page would have to be put in the "purpose" page.

**Comment by schwesig** [comment]
closed https://github.com/operate-first/operate-first.github.io/issues/80

**Comment by schwesig** [comment]
/do-not-merge work-in-progress
waiting for (if these 2 things are solved, the do-not-merge can be removed:

- [ ] resolve conflicting files src/pages/about.js
- [ ] @durandom final check

**Comment by traytorous** [comment]
Closing this pull request. I will be working on durandom's fork.

**Pull request closed without merging**
