### PR TITLE
update index page, add CTA buttons

### PR DESCRIPTION
**Pull request by schwesig**
using more generic op1st URL shortener
adding 2 more CTA (call to action) buttons on the index page (one is for the meetup)

### CODE REVIEW

**Comment by quaid** [comment]
Hey Thorsten, thanks for the idea and PR. A few things occur to me

1. "MeetUp" is a commercial service I don't believe we're using? I'm aware we've been using it in a generic way, as many people do, but I think we need something more accurate that isn't a trademark.
2. From a design standpoint, I wonder if it's distracting having more than one CTA?
3. Will I recognize the value of the content we have on YouTube, I'm not sure the link makes sense to be so front and center. People looking for social media will look for the social media links, and there should be a YouTube one as well. I would only expect a major all focus CTA to be on YouTube if the point of our project was something to do with YouTube.

Perhaps what is needed here is a new landing page to organize this range of interesting content? I hesitate to suggest a new menu item but it could be a sub menu item?

**Comment by schwesig** [comment]
I should have splitted the update into more than one commit. But I need the meetup new schedule. I will start a new one.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
@schwesig I'm a bit confused by the previous comments, do you want to proceed with this PR or not?

**Comment by schwesig** [comment]
ideas about meetup
https://grammarhow.com/meetup-meet-up-or-meet-up/

**Comment by schwesig** [comment]
keeping it on hold to discuss.
I will split the two topics (meet up & design, and calendar update) into two PRs

**Comment by schwesig** [comment]
ideas about meet up
- https://grammarhow.com/meetup-meet-up-or-meet-up/
- https://www.oxfordlearnersdictionaries.com/definition/english/meetup?q=meetup

from this I would say, meetup could be ok, as long as we don't use capitals MeetUp vs meetup?
other ideas are meet up or meet-up

**Comment by schwesig** [comment]
PR splitted into this
- https://github.com/operate-first/operate-first.github.io/pull/222 (index page changes, discussion meet up name)
and
- #223 update meet up page/ agenda for next meeting

**Pull request merged**
