### PR TITLE
delete sre-coloring-book / index.mdx

### PR DESCRIPTION
**Pull request by schwesig**
unpublish the sre-coloring-book / index.mdx until it is finished

### CODE REVIEW

**Comment by schwesig** [comment]
please check, the post is not yet ready to be published
/cc @traytorous
/cc @quaid
/cc @durandom

**Comment by quaid** [comment]
Thanks again for making this PR, @schwesig. I checked with Jeremy, it turns out the coloring book is getting published this week, and he wants us to leave the post live for him to fill out soon. I'll close this PR, and thanks for working it out quickly with me in channels.

**Comment by schwesig** [comment]
@quaid 
Thanks for checking

**Pull request closed without merging**
