### PR TITLE
new blog based on lekoart-core

### PR DESCRIPTION
**Pull request by durandom**
@traytorous have a look at this, it's just using the `blog-core` and building a blog page.
I'll work a bit more on it to also link the actual article, but I think this is least intrusive way to use the core blogging capabilities and still retain our mantine UI.

If you like I can walk you through it and help to setup collaboration by pushing to my branch

### CODE REVIEW

**Comment by durandom** [comment]
Now the article list also links to the post and the posts are rendered

**Comment by traytorous** [comment]
Hey @durandom I'm sorry for the late response. I was busy working on the mid-point presentation. I just looked at your code and tried to run it. There is an error in it. In src/post.tsx you forgot to capitalize layout. import { Layout } from "./layout" -> import { Layout } from "./layout". I can see about meeting with you early in the morning. Also would you like me to delete my fork and just work on yours? It's up to you :)

**Comment by traytorous** [comment]
I believe that this pull request should be merged into the main repo. Afterwards we can create another pull request for detailing the blog page better.

**Comment by durandom** [comment]
@traytorous I rebased the PR and squashed all commits.
Let's make the blog index and article page look nice first, otherwise it'll be a downgrade from the current blog.

* blog articles as cards
* blog entry shows all the available metadata (author, etc, as in e.g. https://www.operate-first.cloud/blog/kube-con-valencia-eu-2022-trip-report)

Let me know if you have spare cycles to work on that

**Comment by quaid** [comment]
> @traytorous I rebased the PR and squashed all commits. Let's make the blog index and article page look nice first, otherwise it'll be a downgrade from the current blog.
>

-1
- I disagree it's a downgrade
- I think any improvement is better than waiting
- Full explanation:

OK, I caught up with Thorsten who let me know the three of you had decided these things would happen before the merge. But let me catch Marcel up on the thinking behind why I asked Trey to make his above comment:

Right now going from front page to the blog is __very__ jarring for the reader, it looks like a completely different website.

If we merge the work where it stands right now (and has for a few weeks), the jarring is removed and replaced with the reader thinking "oh, this is unfinished." But "almost done and unfinished" is far better than "did I just go to a different website?" for a UX.

So I asked Trey to suggest we split out the work into two blog posts so we can evolve things.

> * blog articles as cards
> * blog entry shows all the available metadata (author, etc, as in e.g. https://www.operate-first.cloud/blog/kube-con-valencia-eu-2022-trip-report)
> 
> Let me know if you have spare cycles to work on that

This is the other part of the concern. Right now, Trey can have a merged PR and go on with his school semester ending with that accomplishment. Or we can keep this PR open and mess around until it's perfect, but probably not by waiting for Trey's spare cycles.

So my strong recommendation/desire is to merge this PR as-is and create a new issue/start a PR to cover the formatting of the ToC of blogs and how the blog entry itself appears.

**Comment by durandom** [comment]
> If we merge the work where it stands right now (and has for a few weeks), the jarring is removed and replaced with the reader thinking "oh, this is unfinished." But "almost done and unfinished" is far better than "did I just go to a different website?" for a UX.

@quaid ok, convinced. I'll clean this up and push forward. Thanks for the detailed reasoning

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
