### PR TITLE
Made things* click more noticable

### PR DESCRIPTION
**Pull request by bryanmontalvan**
## Description: 
This PR makes the `things*` link in the hero-description more noticeable by changing it's color to match the logo's primary color along with adding hover affects

**List of changes:**
- Made "things*" yellow 
- Giving the text a hover affect
    - Color changes to logo secondary color
    - Underline is shown on hover

## Issues
Related to #63

### CODE REVIEW

**Review by schwesig — APPROVED** [review]
/lgtm
/approve
thanks @bryanmontalvan for picking up our discussion

**Comment by quaid** [comment]
f*-yes @bryanmontalvan that is quite nice, I love not only the color change but how the underline appears making it clear it's a link after the yellow makes it stand out that it's something. I like the asterisk there still I think, as a secondary-visual cue that it's not only something but possibly a magical hyperlink-footnote.

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

**Comment by bryanmontalvan** [comment]
Going to merge this now

**Pull request merged**
